export const PERMISSIONS = {
  VIEW_USERS: "view_users",
  EDIT_USER_ROLE: "edit_user_role",
  VIEW_LEADS: "view_leads",
  CREATE_LEADS: "create_leads",
  EDIT_LEADS: "edit_leads",
  DELETE_LEADS: "delete_leads",
  EDIT_LEAD_STATUS: "edit_lead_status",
  VIEW_BITACORA: "view_bitacora",
  CREATE_BITACORA: "create_bitacora",
  EDIT_BITACORA: "edit_bitacora",
  DELETE_BITACORA: "delete_bitacora",
  VIEW_ROLES: "view_roles",
  MANAGE_ROLES: "manage_roles",
  MANAGE_GLOBAL_SETTINGS: "manage_global_settings",
} as const;
